container:
  image: cirrusci/android-sdk:24
  cpu: 4
  memory: 10G

env:
  CI: "true"
  BUILD_TOOLS: "29.0.2"
  ANDROID_API: "24"
  EMU_FLAVOR: default
  ANDROID_ABI: armeabi-v7a
  ADB_INSTALL_TIMEOUT: "10" # minutes
  KINVEY_APP_KEY: ENCRYPTED[8471c9d1a011d1632ad737a5686ce7e131384faabd193322f6c47e902e034ae8d329f4a1c05b7f0a6801d8332e1ee2d1]
  KINVEY_APP_SECRET: ENCRYPTED[122cdf1a7a68e55b0e39a81c10256708cdc0e317dd47af5f2724de52fea530d9f7ecc6907069b053a27ec80fa685ca7f]

task:
  name: Cirrus CI
  env:
    matrix:
      - PACKAGE: store.data
      - PACKAGE: store.file
      - PACKAGE: store.user
      - PACKAGE: store.datastore
  nproc_script: nproc
  free_script: free -h
  # apt_update_script: sudo apt update
  # apt_install_script: sudo apt install libpulse0 libglu1-mesa lib32z1 qemu-kvm libvirt0 virt-manager -y
  accept_licenses_script: echo -e "y\ny\ny\ny\ny" | sdkmanager --licenses
  # repositories_cfg_script: echo 'count=0' > ~/.android/repositories.cfg
  sdkmanager_update_script: sdkmanager --update
  # install_platform_tools_script: echo y | sdkmanager "platform-tools"
  # install_tools_script: echo y | sdkmanager "tools"
  install_build_tools_script: echo y | sdkmanager "build-tools;$BUILD_TOOLS"
  # install_platform_emulator_script: echo y | sdkmanager "platforms;android-28"
  install_platform_emulator_script: echo y | sdkmanager "platforms;android-$ANDROID_API"
  # install_extras_script: echo y | sdkmanager "extras;android;m2repository"
  install_image_script: echo y | sdkmanager "system-images;android-$ANDROID_API;$EMU_FLAVOR;$ANDROID_ABI"
  kinvey_properties_appkey_script: sed -i "s/app.key=<YOUR_APP_KEY_HERE>/app.key=$KINVEY_APP_KEY/g" android-lib/src/androidTest/assets/kinvey.properties
  kinvey_properties_appsecret_script: sed -i "s/app.secret=<YOUR_APP_SECRET_HERE>/app.secret=$KINVEY_APP_SECRET/g" android-lib/src/androidTest/assets/kinvey.properties
  # local_properties_script: echo sdk.dir=$ANDROID_HOME > local.properties
  # cat_local_properties_script: cat local.properties
  # build_script: ./gradlew clean release --no-daemon
  assemble_script: ./gradlew assemble assembleAndroidTest
  create_device_script:
    echo no | avdmanager create avd --force
        -n test
        -k "system-images;android-$ANDROID_API;$EMU_FLAVOR;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
        -avd test
        -no-audio
        -no-window
  # start_emulator_background_script:
  #   $ANDROID_HOME/emulator/emulator
  #   -verbose
  #   -avd test
  #   -no-accel
  #   -no-snapshot
  #   -no-audio
  #   -no-window
  #   -gpu off
  #   -no-boot-anim
  #   -camera-back none
  #   -camera-front none
  #   -selinux permissive
  #   -qemu -m 2048
  # wait_for_emulator_script:
  #   - adb wait-for-device
  #   - adb shell input keyevent 82
  wait_for_emulator_script: adb wait-for-device
  input_keyevent_script: adb shell input keyevent 82
  emulator_api_level_script: adb shell getprop ro.build.version.sdk
  emulator_boot_animation_script: while [ "`adb shell getprop init.svc.bootanim | tr -d '\r' `" != "stopped" ] ; do sleep 1; done
  emulator_bootanim_exit_script: while [ "`adb shell getprop service.bootanim.exit | tr -d '\r' `" != "1" ] ; do sleep 1; done
  emulator_boot_completed_script: while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done
  getprop_script: adb shell getprop
  test_script: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=com.kinvey.androidTest.$PACKAGE -PdisablePreDex --stacktrace --no-daemon
