language: android
jdk: oraclejdk8
dist: precise
sudo: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
 global:
  - ANDROID_API=23
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS=25.0.0
  - ADB_INSTALL_TIMEOUT=10 # minutes
  - GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
before_script:
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - mksdcard -l mySdCard 1024M mySdCardFile.img
  - emulator -memory 2048 -avd test -sdcard mySdCardFile.img -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew --stop
script: 
  - ./gradlew clean connectedAndroidTest -PdisablePreDex --stacktrace release --no-daemon

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f75e0e13-72a2-40f6-adee-d04e9cf62137
  