/*
 *  Copyright (c) 2016, Kinvey, Inc. All rights reserved.
 *
 * This software is licensed to you under the Kinvey terms of service located at
 * http://www.kinvey.com/terms-of-use. By downloading, accessing and/or using this
 * software, you hereby accept such terms of service  (and any agreement referenced
 * therein) and agree that you have read, understand and agree to be bound by such
 * terms of service and are of legal age to agree to such terms with Kinvey.
 *
 * This software contains valuable confidential and proprietary information of
 * KINVEY, INC and is subject to applicable licensing agreements.
 * Unauthorized reproduction, transmission or distribution of this file and its
 * contents is a violation of applicable laws.
 *
 */

package com.kinvey.java.model;

import com.google.api.client.json.GenericJson;
import com.google.api.client.util.Data;
import com.google.api.client.util.Key;

import java.util.Map;

/**
 * This class maintains information about a file that has been stored with Kinvey.  Every file has a unique ID, as well as other attributes
 * including but not limited too: filename, size, mimetype, acl, and a public access flag.
 *
 *
 * This object can also maintain any custom attributes, which can be set via accessor methods provided by {@link GenericJson}
 *
 * @author edwardf
 */
public class FileMetaData extends GenericJson {


    @Key("_id")
    private String id;

    @Key("_filename")
    private String fileName;

    @Key("size")
    private long size;

    @Key("mimeType")
    private String mimetype;

    @Key("_public")
    private boolean _public = false;

    @Key("_acl")
    private KinveyMetaData.AccessControlList acl;

    @Key("_kmd")
    private KinveyMetaData kinveyMetaData;

    @Key("_uploadURL")
    private String uploadUrl;

    @Key("_downloadURL")
    private String downloadURL;

    /// Expiration data of the 'downloadURL'.
    private Data expiresAt;

    private Map<String, String> uploadHeaders;

    private Map<String, Object> resumeDownloadData;

    private String etag;

    private String path;

    private String pathUrl;

    /**
     * Create a new instance, without setting any fields
     *
     * If an ID is not set, it will be auto-generated by the service
     *
     */
    public FileMetaData() {
    }

    /**
     * Create a new instance, and set the id of the file
     *
     * @param id - the _id of the new file meta data
     */
    public FileMetaData(String id){
        setId(id);
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public long getSize() {
        return size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public String getMimetype() {
        return mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public KinveyMetaData.AccessControlList getAcl() {
        return acl;
    }

    public void setAcl(KinveyMetaData.AccessControlList acl) {
        this.acl = acl;
    }

    public String getUploadUrl() {
        return uploadUrl;
    }

    public void setUploadUrl(String uploadUrl) {
        this.uploadUrl = uploadUrl;
    }

    public String getDownloadURL() {
        return downloadURL;
    }

    public void setDownloadURL(String downloadURL) {
        this.downloadURL = downloadURL;
    }

    public boolean isPublic() {
        return this._public;
    }

    public void setPublic(boolean isPublic) {
        this._public = isPublic;
    }

    public KinveyMetaData getKinveyMetaData() {
        return kinveyMetaData;
    }

    public void setKinveyMetaData(KinveyMetaData kinveyMetaData) {
        this.kinveyMetaData = kinveyMetaData;
    }

    public Map<String, String> getUploadHeaders() {
        return uploadHeaders;
    }

    public void setUploadHeaders(Map<String, String> uploadHeaders) {
        this.uploadHeaders = uploadHeaders;
    }

    public Map<String, Object> getResumeDownloadData() {
        return resumeDownloadData;
    }

    public void setResumeDownloadData(Map<String, Object> resumeDownloadData) {
        this.resumeDownloadData = resumeDownloadData;
    }

    public String getEtag() {
        return etag;
    }

    public void setEtag(String etag) {
        this.etag = etag;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getPathUrl() {
        return pathUrl;
    }

    public void setPathUrl(String pathUrl) {
        this.pathUrl = pathUrl;
    }
}
